local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 4.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: True
      width: 10
      height: 10
      resolution: 0.02
      footprint: "[[1.485, 0.5], [1.485, -0.5], [-0.35, -0.5], [-0.35, 0.5]]"
      always_send_full_costmap: True
      plugins: ["stvl_layer"]
      stvl_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: true
        voxel_decay: 45.
        decay_model: 0
        voxel_size: 0.02
        track_unknown_space: false
        unknown_threshold: 7
        mark_threshold: 1
        update_footprint_enabled: true
        combination_method: 1
        origin_z: 0.0
        publish_voxel_map: true
        transform_tolerance: 0.2
        mapping_mode: false
        map_save_duration: 120.0
        observation_sources: pointcloud_kinect_dk_mark pointcloud_kinect_dk_clear pointcloud_left_mark pointcloud_left_clear pointcloud_right_mark pointcloud_right_clear
        pointcloud_kinect_dk_mark:
          data_type: PointCloud2
          topic: /points2/filtered
          marking: true
          clearing: false
          obstacle_range: 3.0
          min_obstacle_height: 0.05
          max_obstacle_height: 0.7
          inf_is_valid: false
          filter: "voxel"
          voxel_min_points: 5
          clear_after_reading: true
        pointcloud_kinect_dk_clear:
          data_type: PointCloud2
          topic: /points2/filtered
          marking: false
          clearing: true
          max_z: 15.0   # with lower values, kinect obstacles might not get cleaned correctly.
          min_z: 0.1
          decay_acceleration: 4.0
          vertical_fov_angle: 1.565
          horizontal_fov_angle: 1.585
        pointcloud_left_mark:
          data_type: PointCloud2
          topic: /realsense_left/depth/color/points
          marking: true
          clearing: false
          obstacle_range: 3.0
          min_obstacle_height: 0.04
          max_obstacle_height: 1.0
          inf_is_valid: false
          filter: "voxel"
          voxel_min_points: 5
          clear_after_reading: true
        pointcloud_left_clear:
          data_type: PointCloud2
          topic: /realsense_left/depth/color/points
          marking: false
          clearing: true
          max_z: 13.0
          min_z: 0.2
          decay_acceleration: 3.0
          vertical_fov_angle: 0.8
          horizontal_fov_angle: 1.08
        pointcloud_right_mark:
          data_type: PointCloud2
          topic: /realsense_right/depth/color/points
          marking: true
          clearing: false
          obstacle_range: 3.0
          min_obstacle_height: 0.04
          max_obstacle_height: 1.0
          inf_is_valid: false
          filter: "voxel"
          voxel_min_points: 5
          clear_after_reading: true
        pointcloud_right_clear:
          data_type: PointCloud2
          topic: /realsense_right/depth/color/points
          marking: false
          clearing: true
          max_z: 13.0
          min_z: 0.2
          decay_acceleration: 3.0
          vertical_fov_angle: 0.8
          horizontal_fov_angle: 1.08
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

rosbag_recorder:
  ros__parameters:
    topics: [ # Without leading slash (/) if it is to be prepended with namespace
      "global_costmap/costmap",
      "global_plan",
      "local_costmap/costmap",
      "local_costmap/published_footprint",
      "local_costmap/voxel_grid",
      "action_server_error_message",
      "obstacles_markers",
      "teb_markers",
      "teb_poses",
      "tf",
      "tf_static",
      "create_feasible_putdown_goal",
      "joint_states",
      "cmd_vel",
      "cmd_vel_smoothed",
      "tricycle_controller/cmd_ackermann",
      "speed_limit",
      "speed_limit_close_vehicle",
      "speed_limit_w2mo_path",
      "odometry/filtered",
      "load_sensor_status",
      "diagnostics",
      "bt_logs_publisher/behavior_tree_log",
      "/clock",
      "/rosout",
      "lidar_field",
     # uncomment when fork camera feed in rosbag is needed
     #points2/filtered
     #realsense_right/color/image_raw
     #realsense_left/color/image_raw
    ]
    bags_dir: "/data/rosbags" # Without last slash (/). If changed also change /code/deep_cv/docker/rosbags
    max_duration: 400
    upload_enabled: True
    storage_format: mcap
